spring:
    datasource:
        url: jdbc:h2:file:./data/coffe_test
        driver-class-name: org.h2.Driver
        username: pepo
        password: 
        
    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        hibernate:
            ddl-auto: validate
            
    h2:
        console:
            enabled: true
            path: /console
            settings:
                web-allow-others: true
